### ISSUE TITLE
Style Guide Component API

### ISSUE THREAD

**Issue by nmcclay** [forever-inc/forever-style-guide#64]
It would be nice if we could pull in the navbar via a helper method provided by the style guide. 

Currently we could do with by just changing our existing partials out:

instead of including:
``` 
<%= render 'layouts/navigation' %>
```

we could do something like 
``` 
<%= render 'forever_style_guide/sections/navigation/marketing' %>
```

But I think a much more desirable option would just be to have something like:
```
<%=- forever_style_guide_header user: @user, class: "optional-class" %>
```
with user and class as optional pass throughs to the partial.  The advantage here is we could completely restructure the user profile appearance without having to update multiple apps or javascript snippets.

**Comment by schweitzdesign** [comment]
Especially relevant for the navigation would be a means to do this that is environment agnostic as well, as currently many of the store links at www are hardcoded to production and this gets very confusing when both developing and testing in non-production environments.
