### ISSUE TITLE
fix box & text shadows

### ISSUE THREAD

**Issue by katywatkins** [forever-inc/forever-style-guide#74]
* text-shadow doesn't need commas (check www testimonials)
* box-shadow mixin needs to address spread value (check home and other product pages)

.hero-block-blur should end up with `box-shadow: 0 0 4px 2px rgba(67,68,69,0.25);` and match screenshots below
<img width="1238" alt="screen shot 2016-04-26 at 3 28 28 pm" src="https://cloud.githubusercontent.com/assets/1926679/14831439/ca8b4850-0bc3-11e6-95aa-ebe53c77d37f.png">
<img width="1238" alt="screen shot 2016-04-26 at 3 28 13 pm" src="https://cloud.githubusercontent.com/assets/1926679/14831441/cc63a4c4-0bc3-11e6-8251-f81186b2e7ca.png">

**Comment by schweitzdesign** [comment]
![screen shot 2016-04-26 at 4 18 17 pm](https://cloud.githubusercontent.com/assets/3814998/14832913/825724bc-0bca-11e6-9530-f92a7ccd08de.png)


We'll need to address these mixins obviously, but more generally I think the hero's could totally do w/ out the box-shadow. What do you think @katywatkins

**Comment by katywatkins** [comment]
On the underlying hero block? Definitely!

**Comment by katywatkins** [comment]
Fixed: https://github.com/forever-inc/forever-style-guide/pull/76
