### ISSUE TITLE
Font-face-light typo

### ISSUE THREAD

**Issue by schweitzdesign** [forever-inc/forever-style-guide#75]
See fonts.scss - we're redeclaring Proxima Nova Regular inadvertently. 

```
@include fontFace('proxima_nova-light', 'ProximaNova-Reg-webfont');
````

Currently this will only effect the testimonial styling and the overview text on the guarantee page - both only on www.

![screen shot 2016-04-27 at 9 07 40 am](https://cloud.githubusercontent.com/assets/3814998/14853007/a6be897a-0c57-11e6-9220-2f9847adcb80.png)

**Comment by katywatkins** [comment]
fixed: https://github.com/forever-inc/forever-style-guide/pull/76
